@echo OFF
echo ERR THIS FILE HAS NO CODE
echo ERR THIS FILE HAS NO CODE
echo ERR THIS FILE HAS NO CODE
echo ERR THIS FILE HAS NO CODE
echo ERR THIS FILE HAS NO CODE
echo ERR THIS FILE HAS NO CODE
echo ERR THIS FILE HAS NO CODE
echo ERR THIS FILE HAS NO CODE
echo ERR THIS FILE HAS NO CODE
echo ERR THIS FILE HAS NO CODE
echo ERR THIS FILE HAS NO CODE
echo ERR THIS FILE HAS NO CODE
echo ERR THIS FILE HAS NO CODE
echo ERR THIS FILE HAS NO CODE
echo ERR THIS FILE HAS NO CODE
echo ERR THIS FILE HAS NO CODE
echo ERR THIS FILE HAS NO CODE
echo ERR THIS FILE HAS NO CODE
echo ERR THIS FILE HAS NO CODE
echo ERR THIS FILE HAS NO CODE
pause >nul
